import { cleanEnv, str } from 'envalid';

const rawEnv = {
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_TELEGRAM_BOT_NAME: process.env.NEXT_PUBLIC_TELEGRAM_BOT_NAME,
};

const env = cleanEnv(rawEnv, {
  NEXT_PUBLIC_FIREBASE_API_KEY: str(),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: str(),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: str(),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: str(),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: str(),
  NEXT_PUBLIC_FIREBASE_APP_ID: str(),
  NEXT_PUBLIC_TELEGRAM_BOT_NAME: str(),
});

export const FIREBASE_API_KEY = env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID =
  env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = env.NEXT_PUBLIC_FIREBASE_APP_ID;
export const TELEGRAM_BOT_NAME = env.NEXT_PUBLIC_TELEGRAM_BOT_NAME;
